#!/usr/bin/env bash

# Pretty pictures
function e_header()  { echo -e "\n\033[1m$@\033[0m";      }
function e_success() { echo -e " \033[1;32m✔\033[0m  $@"; }
function e_error()   { echo -e " \033[1;31m✖\033[0m  $@"; }
function e_arrow()   { echo -e "\033[1;34m==>\033[0m $@"; }

e_header "Setting OS X defaults"

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until `default` has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

###############################################################################
e_header "General UI/UX"
###############################################################################

e_arrow "Setting computer name"
sudo scutil --set ComputerName "Icarus"
sudo scutil --set HostName "Icarus"
sudo scutil --set LocalHostName "Icarus"
sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.smb.server NetBIOSName -string "Icarus"

e_arrow "Disabling Guest account"
defaults write /Library/Preferences/com.apple.AppleFileServer guestAccess -bool NO
defaults write /Library/Preferences/SystemConfiguration/com.apple.smb.server AllowGuestAccess -bool NO
defaults write /Library/Preferences/com.apple.loginwindow GuestEnabled -bool NO

e_arrow "Setting standby delay to 24 hours"
sudo pmset -a standbydelay 86400

# e_arrow "Disabling sound effects on boot"
# sudo nvram SystemAudioVolume=" "

# e_arrow "Disabling menubar transparency"
# defaults write NSGlobalDomain AppleEnableMenuBarTransparency -bool false

e_arrow "Configuring menubar battery time and percentage"
defaults write com.apple.menuextra.battery ShowPercent -string "NO"
defaults write com.apple.menuextra.battery ShowTime -string "YES"

e_arrow "Hiding Time Machine and Volume menubar icons"
defaults write com.apple.systemuiserver menuExtras -array "/System/Library/CoreServices/Menu Extras/Bluetooth.menu" "/System/Library/CoreServices/Menu Extras/AirPort.menu" "/System/Library/CoreServices/Menu Extras/Battery.menu" "/System/Library/CoreServices/Menu Extras/Clock.menu"

e_arrow "Setting sidebar icon size to small"
defaults write NSGlobalDomain NSTableViewDefaultSizeMode -int 1

e_arrow "Always show scrollbars"
defaults write NSGlobalDomain AppleShowScrollBars -string "Always"
# Possible values: `WhenScrolling`, `Automatic` and `Always`

e_arrow "Increasing window resize speed"
defaults write NSGlobalDomain NSWindowResizeTime -float 0.001

e_arrow "Expanding save panel by default"
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true

e_arrow "Expanding print panel by default"
defaults write NSGlobalDomain PMPrintingExpandedStateForPrint -bool true

e_arrow "Setting disk as default when saving"
defaults write NSGlobalDomain NSDocumentSaveNewDocumentsToCloud -bool false

e_arrow "Automatically quit printer app when print jobs complete"
defaults write com.apple.print.PrintingPrefs "Quit When Finished" -bool true

e_arrow "Disabling confirm open application dialog"
defaults write com.apple.LaunchServices LSQuarantine -bool false

# Try e.g. `cd /tmp; unidecode "\x{0000}" > cc.txt; open -e cc.txt`
e_arrow "Displaying ASCII control characters using caret notation"
defaults write NSGlobalDomain NSTextShowsControlCharacters -bool true

e_arrow "Disabling resume system-wide"
defaults write NSGlobalDomain NSQuitAlwaysKeepsWindows -bool false

e_arrow "Disabling automatic termination of inactive apps"
defaults write NSGlobalDomain NSDisableAutomaticTermination -bool true

# e_arrow "Disabling the crash reporter"
# defaults write com.apple.CrashReporter DialogType -string "none"

e_arrow "Setting Help Viewer windows to non-floating mode"
defaults write com.apple.helpviewer DevMode -bool true

e_arrow "Reveal IP address, hostname, OS version when clicking clock in login window"
sudo defaults write /Library/Preferences/com.apple.loginwindow AdminHostInfo HostName

# e_arrow "Disabling sleep mode"
# systemsetup -setcomputersleep Off > /dev/null

e_arrow "Check for software updates daily"
defaults write com.apple.SoftwareUpdate ScheduleFrequency -int 1

e_arrow "Disabling Notification Center"
launchctl unload -w /System/Library/LaunchAgents/com.apple.notificationcenterui.plist 2> /dev/null

e_arrow "Disabling smart quotes"
defaults write NSGlobalDomain NSAutomaticQuoteSubstitutionEnabled -bool false

e_arrow "Disabling smart dashes"
defaults write NSGlobalDomain NSAutomaticDashSubstitutionEnabled -bool false

###############################################################################
e_header "SSD-specific tweaks"
###############################################################################

e_arrow "Disabling local Time Machine snapshots"
sudo tmutil disablelocal

# e_arrow "Disabling hibernation" # speeds up entering sleep mode
# sudo pmset -a hibernatemode 0

e_arrow "Removing sleep image file" # to save disk space
sudo rm -f /Private/var/vm/sleepimage
# Create a zero-byte file instead…
sudo touch /Private/var/vm/sleepimage
# …and make sure it can’t be rewritten
sudo chflags uchg /Private/var/vm/sleepimage

e_arrow "Disabling sudden motion sensor" # not useful for SSDs
sudo pmset -a sms 0

###############################################################################
e_header "Trackpad, mouse, keyboard, Bluetooth accessories, and input"
###############################################################################

e_arrow "Enabling tap to click for this user and for the login screen"
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true
defaults -currentHost write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
defaults write NSGlobalDomain com.apple.mouse.tapBehavior -int 1

e_arrow "Setting mouse tracking speed"
defaults write NSGlobalDoman com.apple.mouse.scaling 3.0
# defaults delete NSGlobalDoman com.apple.mouse.scaling

e_arrow "Increasing sound quality for Bluetooth headphones/headsets"
defaults write com.apple.BluetoothAudioAgent "Apple Bitpool Min (editable)" -int 40

e_arrow "Enabling full keyboard access for all controls"
# (e.g. enable Tab in modal dialogs)
defaults write NSGlobalDomain AppleKeyboardUIMode -int 3

e_arrow "Enabling scroll gesture with Ctrl (^) modifier to zoom"
defaults write com.apple.universalaccess closeViewScrollWheelToggle -bool true
defaults write com.apple.universalaccess HIDScrollZoomModifierMask -int 262144

e_arrow "Map Caps Lock key to Control" # Maps for all connected keyboards
ioreg -n IOHIDKeyboard -r | grep -E 'VendorID"|ProductID' | awk '{ print $4 }' | paste -s -d'-\n' - | xargs -I{} /usr/bin/defaults -currentHost write -g "com.apple.keyboard.modifiermapping.{}-0" -array "<dict><key>HIDKeyboardModifierMappingDst</key><integer>2</integer><key>HIDKeyboardModifierMappingSrc</key><integer>0</integer></dict>"

e_arrow "Follow the keyboard focus while zoomed in"
defaults write com.apple.universalaccess closeViewZoomFollowsFocus -bool true

e_arrow "Disabling press-and-hold for keys" # in favor of key repeat
defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool false

e_arrow "Setting keyboard repeat rate" # really fast
defaults write NSGlobalDomain KeyRepeat -int 0

e_arrow "Enabling automatic illumination for built-in MacBook keyboard"
defaults write com.apple.BezelServices kDim -bool true

e_arrow "Setting 5 minute timeout for keyboard illumination"
defaults write com.apple.BezelServices kDimTime -int 300

e_arrow "Setting default timezone" # see `systemsetup -listtimezones` for other values
systemsetup -settimezone "America/Detroit" > /dev/null

# e_arrow "Disable auto-correct"
# defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool false

# e_arrow "Disabling iTunes from responding to the keyboard media keys"
# launchctl unload -w /System/Library/LaunchAgents/com.apple.rcd.plist 2> /dev/null

###############################################################################
e_header "Screen"
###############################################################################

e_arrow "Requiring password after sleep or screen saver begins"
defaults write com.apple.screensaver askForPassword -int 1
defaults write com.apple.screensaver askForPasswordDelay -int 30 # 30 seconds

e_arrow "Save screenshots to the desktop"
defaults write com.apple.screencapture location -string "${HOME}/Desktop"

e_arrow "Save screenshots in PNG format" # (other options: BMP, GIF, JPG, PDF, TIFF)
defaults write com.apple.screencapture type -string "png"

# e_arrow "Disabling shadows in screenshots"
# defaults write com.apple.screencapture disable-shadow -bool true

e_arrow "Enabling subpixel font rendering on non-Apple LCDs"
defaults write NSGlobalDomain AppleFontSmoothing -int 2

e_arrow "Enabling HiDPI display modes" # (requires restart)
sudo defaults write /Library/Preferences/com.apple.windowserver DisplayResolutionEnabled -bool true

###############################################################################
e_header "Finder"
###############################################################################

# e_arrow "Finder: allow quitting via ⌘ + Q; doing so will also hide desktop icons"
# defaults write com.apple.finder QuitMenuItem -bool true

# e_arrow "Disabling Finder window and Get Info animations"
# defaults write com.apple.finder DisableAllAnimations -bool true

# e_arrow "Showing icons for hard drives, servers, and removable media on the desktop"
# defaults write com.apple.finder ShowExternalHardDrivesOnDesktop -bool true
# defaults write com.apple.finder ShowHardDrivesOnDesktop -bool true
# defaults write com.apple.finder ShowMountedServersOnDesktop -bool true
# defaults write com.apple.finder ShowRemovableMediaOnDesktop -bool true

# e_arrow "Showing hidden files in Finder"
# defaults write com.apple.finder AppleShowAllFiles -bool true

e_arrow "Showing all filename extensions in Finder"
defaults write NSGlobalDomain AppleShowAllExtensions -bool true

e_arrow "Showing status bar in Finder"
defaults write com.apple.finder ShowStatusBar -bool true

e_arrow "Showing path bar in Finder"
defaults write com.apple.finder ShowPathbar -bool true

e_arrow "Allowing text selection in Quick Look"
defaults write com.apple.finder QLEnableTextSelection -bool true

e_arrow "Displaying full POSIX path as Finder window title"
defaults write com.apple.finder _FXShowPosixPathInTitle -bool true

e_arrow "Enabling searching of the current folder by default"
defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"

e_arrow "Disabling file extension change warning"
defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false

e_arrow "Enabling spring loading for directories"
defaults write NSGlobalDomain com.apple.springing.enabled -bool true

e_arrow "Removing spring loading delay for directories"
defaults write NSGlobalDomain com.apple.springing.delay -float 0

e_arrow "Disabling creation of .DS_Store files on network volumes"
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true

e_arrow "Disabling disk image verification"
defaults write com.apple.frameworks.diskimages skip-verify -bool true
defaults write com.apple.frameworks.diskimages skip-verify-locked -bool true
defaults write com.apple.frameworks.diskimages skip-verify-remote -bool true

e_arrow "Automatically open a new Finder window when a volume is mounted"
defaults write com.apple.frameworks.diskimages auto-open-ro-root -bool true
defaults write com.apple.frameworks.diskimages auto-open-rw-root -bool true
defaults write com.apple.finder OpenWindowForNewRemovableDisk -bool true

# e_arrow "Show item info near icons on the desktop and in other icon views"
# /usr/libexec/PlistBuddy -c "Set :DesktopViewSettings:IconViewSettings:showItemInfo true" ~/Library/Preferences/com.apple.finder.plist
# /usr/libexec/PlistBuddy -c "Set :FK_StandardViewSettings:IconViewSettings:showItemInfo true" ~/Library/Preferences/com.apple.finder.plist
# /usr/libexec/PlistBuddy -c "Set :StandardViewSettings:IconViewSettings:showItemInfo true" ~/Library/Preferences/com.apple.finder.plist

# e_arrow "Show item info to the right of the icons on the desktop"
# /usr/libexec/PlistBuddy -c "Set DesktopViewSettings:IconViewSettings:labelOnBottom false" ~/Library/Preferences/com.apple.finder.plist

e_arrow "Enabling snap-to-grid for the desktop and icon views"
/usr/libexec/PlistBuddy -c "Set :DesktopViewSettings:IconViewSettings:arrangeBy grid" ~/Library/Preferences/com.apple.finder.plist
/usr/libexec/PlistBuddy -c "Set :FK_StandardViewSettings:IconViewSettings:arrangeBy grid" ~/Library/Preferences/com.apple.finder.plist
/usr/libexec/PlistBuddy -c "Set :StandardViewSettings:IconViewSettings:arrangeBy grid" ~/Library/Preferences/com.apple.finder.plist

e_arrow "Increasing grid spacing for desktop and icon views"
/usr/libexec/PlistBuddy -c "Set :DesktopViewSettings:IconViewSettings:gridSpacing 100" ~/Library/Preferences/com.apple.finder.plist
/usr/libexec/PlistBuddy -c "Set :FK_StandardViewSettings:IconViewSettings:gridSpacing 100" ~/Library/Preferences/com.apple.finder.plist
/usr/libexec/PlistBuddy -c "Set :StandardViewSettings:IconViewSettings:gridSpacing 100" ~/Library/Preferences/com.apple.finder.plist

e_arrow "Increasing the size of icons on the desktop and in icon views"
/usr/libexec/PlistBuddy -c "Set :DesktopViewSettings:IconViewSettings:iconSize 80" ~/Library/Preferences/com.apple.finder.plist
/usr/libexec/PlistBuddy -c "Set :FK_StandardViewSettings:IconViewSettings:iconSize 80" ~/Library/Preferences/com.apple.finder.plist
/usr/libexec/PlistBuddy -c "Set :StandardViewSettings:IconViewSettings:iconSize 80" ~/Library/Preferences/com.apple.finder.plist

e_arrow "Setting list view as default Finder view"
# Four-letter codes for the other view modes: `icnv`, `clmv`, `Flwv`
defaults write com.apple.finder FXPreferredViewStyle -string "Nlsv"

e_arrow "Disabling warning before emptying the Trash"
defaults write com.apple.finder WarnOnEmptyTrash -bool false

e_arrow "Setting empty Trash securely as default"
defaults write com.apple.finder EmptyTrashSecurely -bool true

e_arrow "Enabling AirDrop over Ethernet and on unsupported Macs running Lion"
defaults write com.apple.NetworkBrowser BrowseAllInterfaces -bool true

e_arrow "Enabling the MacBook Air SuperDrive on any Mac"
sudo nvram boot-args="mbasd=1"

e_arrow "Showing the ~/Library folder"
chflags nohidden ~/Library

e_arrow "Removing Dropbox’s green checkmark icons in Finder"
file=/Applications/Dropbox.app/Contents/Resources/emblem-dropbox-uptodate.icns
[ -e "${file}" ] && mv -f "${file}" "${file}.bak"

###############################################################################
e_header "Dock and Dashboard"
###############################################################################

e_arrow "Enabling highlight hover effect for the grid view stacks"
defaults write com.apple.dock mouse-over-hilite-stack -bool true

e_arrow "Setting the icon size of Dock items to 36 pixels"
defaults write com.apple.dock tilesize -int 36

e_arrow "Minimize windows into their application’s icon"
defaults write com.apple.dock minimize-to-application -bool true

e_arrow "Enabling spring loading for all Dock items"
defaults write com.apple.dock enable-spring-load-actions-on-all-items -bool true

e_arrow "Showing indicator lights for open applications in the Dock"
defaults write com.apple.dock show-process-indicators -bool true

e_arrow "Setting Dock app icons"
defaults write com.apple.dock persistent-apps -array
defaults write com.apple.dock persistent-apps -array-add '<dict><key>tile-data</key><dict><key>file-data</key><dict><key>_CFURLString</key><string>/Applications/Safari.app</string><key>_CFURLStringType</key><integer>0</integer></dict></dict></dict>'
defaults write com.apple.dock persistent-apps -array-add '<dict><key>tile-data</key><dict><key>file-data</key><dict><key>_CFURLString</key><string>/Applications/Mail.app</string><key>_CFURLStringType</key><integer>0</integer></dict></dict></dict>'
defaults write com.apple.dock persistent-apps -array-add '<dict><key>tile-data</key><dict><key>file-data</key><dict><key>_CFURLString</key><string>/Applications/iTerm.app</string><key>_CFURLStringType</key><integer>0</integer></dict></dict></dict>'
defaults write com.apple.dock persistent-apps -array-add '<dict><key>tile-data</key><dict><key>file-data</key><dict><key>_CFURLString</key><string>/Applications/Messages.app</string><key>_CFURLStringType</key><integer>0</integer></dict></dict></dict>'

# e_arrow "Disabling animation when opening applications from the Dock"
# defaults write com.apple.dock launchanim -bool false

e_arrow "Speeding up Mission Control animations"
defaults write com.apple.dock expose-animation-duration -float 0.2

e_arrow "Disabling grouping windows by application in Mission Control"
# (i.e. use the old Exposé behavior instead)
defaults write com.apple.dock expose-group-by-app -bool false

e_arrow "Disabling Dashboard"
defaults write com.apple.dashboard mcx-disabled -bool true

e_arrow "Disabling Dashboard as a Space"
defaults write com.apple.dock dashboard-in-overlay -bool true

e_arrow "Disabling automatic rearranging of Spaces based on most recent use"
defaults write com.apple.dock mru-spaces -bool false

# e_arrow "Removing auto-hiding Dock delay"
# defaults write com.apple.dock autohide-delay -float 0

# e_arrow "Removing animation when hiding/showing the Dock"
# defaults write com.apple.dock autohide-time-modifier -float 0

# e_arrow "Enabling 2D Dock"
# defaults write com.apple.dock no-glass -bool true

e_arrow "Enabling automatic hide and show of the Dock"
defaults write com.apple.dock autohide -bool true

e_arrow "Enabling translucent Dock icons for hidden applications"
defaults write com.apple.dock showhidden -bool true

e_arrow "Resetting Launchpad"
find ~/Library/Application\ Support/Dock -name "*.db" -maxdepth 1 -delete

e_arrow "Adding iOS Simulator to Launchpad"
sudo ln -sf /Applications/Xcode.app/Contents/Applications/iPhone\ Simulator.app /Applications/iOS\ Simulator.app

###############################################################################
e_header "Safari & WebKit"
###############################################################################

e_arrow "Setting home page to 'about:blank'"
defaults write com.apple.Safari HomePage -string "about:blank"

e_arrow "Setting new windows and tabs to a blank page"
defaults write com.apple.Safari NewWindowBehavior -int 1
defaults write com.apple.Safari NewTabBehavior -int 1

e_arrow "Preventing opening of 'safe' files automatically after downloading"
defaults write com.apple.Safari AutoOpenSafeDownloads -bool false

e_arrow "Enabling Backspace key to go to the previous page in history"
defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2BackspaceKeyNavigationEnabled -bool true

# e_arrow "Hiding bookmarks bar"
# defaults write com.apple.Safari ShowFavoritesBar -bool false

e_arrow "Disabling thumbnail cache for History and Top Sites"
defaults write com.apple.Safari DebugSnapshotsUpdatePolicy -int 2

e_arrow "Enabling debug menu"
defaults write com.apple.Safari IncludeInternalDebugMenu -bool true

e_arrow "Configuring search banners to 'Contains' instead of 'Starts With'"
defaults write com.apple.Safari FindOnPageMatchesWordStartsOnly -bool false

e_arrow "Removing unused icons from bookmarks bar"
defaults write com.apple.Safari ProxiesInBookmarksBar "()"

e_arrow "Enabling Develop menu and Web Inspector"
defaults write com.apple.Safari IncludeDevelopMenu -bool true
defaults write com.apple.Safari WebKitDeveloperExtrasEnabledPreferenceKey -bool true
defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled -bool true

e_arrow "Adding context menu item for Web Inspector in web views"
defaults write NSGlobalDomain WebKitDeveloperExtras -bool true

###############################################################################
e_header "Mail"
###############################################################################

# e_arrow "Disabling send and reply animations"
# defaults write com.apple.mail DisableReplyAnimations -bool true
# defaults write com.apple.mail DisableSendAnimations -bool true

e_arrow "Setting email address copy as 'foo@example.com' instead of 'Foo Bar <foo@example.com>'"
defaults write com.apple.mail AddressesIncludeNameOnPasteboard -bool false

# e_arrow "Adding the keyboard shortcut ⌘ + Enter to send an email"
# defaults write com.apple.mail NSUserKeyEquivalents -dict-add "Send" -string "@\\U21a9"

e_arrow "Displaying emails in threaded mode, sorted by date descending"
defaults write com.apple.mail DraftsViewerAttributes -dict-add "DisplayInThreadedMode" -string "yes"
defaults write com.apple.mail DraftsViewerAttributes -dict-add "SortedDescending" -string "yes"
defaults write com.apple.mail DraftsViewerAttributes -dict-add "SortOrder" -string "received-date"

e_arrow "Disabling inline attachments"
defaults write com.apple.mail DisableInlineAttachmentViewing -bool true

# e_arrow "Disabling automatic spell checking"
# defaults write com.apple.mail SpellCheckingBehavior -string "NoSpellCheckingEnabled"

###############################################################################
e_header "Spotlight"
###############################################################################

e_arrow "Hiding tray-icon and helper"
sudo chmod 600 /System/Library/CoreServices/Search.bundle/Contents/MacOS/Search

e_arrow "Disabling indexing for any volume that's mounted and hasn't yet been indexed"
# Use `sudo mdutil -i off "/Volumes/foo"` to stop indexing any volume.
sudo defaults write /.Spotlight-V100/VolumeConfiguration Exclusions -array "/Volumes"

e_arrow "Changing indexing order and disabling some file types"
defaults write com.apple.spotlight orderedItems -array \
	'{"enabled" = 1;"name" = "APPLICATIONS";}' \
	'{"enabled" = 1;"name" = "SYSTEM_PREFS";}' \
	'{"enabled" = 1;"name" = "DIRECTORIES";}' \
	'{"enabled" = 1;"name" = "PDF";}' \
	'{"enabled" = 1;"name" = "DOCUMENTS";}' \
	'{"enabled" = 1;"name" = "SPREADSHEETS";}' \
	'{"enabled" = 1;"name" = "CONTACT";}' \
	'{"enabled" = 1;"name" = "SOURCE";}' \
	'{"enabled" = 1;"name" = "EVENT_TODO";}' \
	'{"enabled" = 0;"name" = "FONTS";}' \
	'{"enabled" = 0;"name" = "MESSAGES";}' \
	'{"enabled" = 0;"name" = "IMAGES";}' \
	'{"enabled" = 0;"name" = "BOOKMARKS";}' \
	'{"enabled" = 0;"name" = "MUSIC";}' \
	'{"enabled" = 0;"name" = "MOVIES";}' \
	'{"enabled" = 0;"name" = "PRESENTATIONS";}'

e_arrow "Loading new settings before rebuilding index"
killall mds > /dev/null 2>&1

e_arrow "Enabling indexing for main volume"
sudo mdutil -i on / > /dev/null

e_arrow "Rebuilding index from scratch"
sudo mdutil -E / > /dev/null

###############################################################################
e_header "Terminal & iTerm 2"
###############################################################################

e_arrow "Only use UTF-8 in Terminal"
defaults write com.apple.terminal StringEncodings -array 4

e_arrow "Installing Solarized themes for Terminal"
open "$BASH_SOURCE[0]/../../config/Solarized Dark.terminal"
sleep 1
open "$BASH_SOURCE[0]/../../config/Solarized Light.terminal"
sleep 1
defaults write com.apple.terminal "Default Window Settings" -string "Solarized Dark"
defaults write com.apple.terminal "Startup Window Settings" -string "Solarized Dark"

# e_arrow "Enabling `focus follows mouse` for Terminal and all X11 apps"
# i.e. hover over a window and start typing in it without clicking first
# defaults write com.apple.terminal FocusFollowsMouse -bool true
# defaults write org.x.X11 wm_ffm -bool true

e_arrow "Installing Solarized themes for iTerm"
open "$BASH_SOURCE[0]/../../config/Solarized Dark.itermcolors"
sleep 1
open "$BASH_SOURCE[0]/../../config/Solarized Light.itermcolors"
sleep 1

e_arrow "Disabling prompt when quitting iTerm"
defaults write com.googlecode.iterm2 PromptOnQuit -bool false

###############################################################################
e_header "Time Machine"
###############################################################################

e_arrow "Preventing prompt to use new hard drives as backup volume"
defaults write com.apple.TimeMachine DoNotOfferNewDisksForBackup -bool true

e_arrow "Disabling local Time Machine backups"
hash tmutil &> /dev/null && sudo tmutil disablelocal

###############################################################################
e_header "Address Book, Dashboard, Calendar, TextEdit, and Disk Utility"
###############################################################################

e_arrow "Enabling the debug menu in Address Book"
defaults write com.apple.addressbook ABShowDebugMenu -bool true

e_arrow "Enabling Dashboard dev mode" # allows keeping widgets on the desktop
defaults write com.apple.dashboard devmode -bool true

e_arrow "Setting plain text as default mode for new TextEdit documents"
defaults write com.apple.TextEdit RichText -int 0

e_arrow "Setting UTF-8 as default for opening and saving files in TextEdit"
defaults write com.apple.TextEdit PlainTextEncoding -int 4
defaults write com.apple.TextEdit PlainTextEncodingForWrite -int 4

e_arrow "Enabling the debug menu in Disk Utility"
defaults write com.apple.DiskUtility DUDebugMenuEnabled -bool true
defaults write com.apple.DiskUtility advanced-image-options -bool true

###############################################################################
e_header "Mac App Store"
###############################################################################

e_arrow "Enabling WebKit Developer Tools"
defaults write com.apple.appstore WebKitDeveloperExtras -bool true

e_arrow "Enabling Debug Menu"
defaults write com.apple.appstore ShowDebugMenu -bool true

###############################################################################
e_header "Messages"
###############################################################################

e_arrow "Disabling automatic emoji substitution" # i.e. use plain text smileys
defaults write com.apple.messageshelper.MessageController SOInputLineSettings -dict-add "automaticEmojiSubstitutionEnablediMessage" -bool false

e_arrow "Disabling smart quotes"
defaults write com.apple.messageshelper.MessageController SOInputLineSettings -dict-add "automaticQuoteSubstitutionEnabled" -bool false

# e_arrow "Disabling continuous spell checking"
# defaults write com.apple.messageshelper.MessageController SOInputLineSettings -dict-add "continuousSpellCheckingEnabled" -bool false

###############################################################################
e_header "Sublime Text"
###############################################################################

e_arrow "Installing Sublime Text settings"
cp -r ../config/Preferences.sublime-settings ~/Library/Application\ Support/Sublime\ Text*/Packages/User/Preferences.sublime-settings 2> /dev/null

###############################################################################
e_header "Transmission"
###############################################################################

e_arrow "Setting '~/Documents/Torrents' as default folder for incomplete downloads"
defaults write org.m0k.transmission UseIncompleteDownloadFolder -bool true
defaults write org.m0k.transmission IncompleteDownloadFolder -string "${HOME}/Documents/Torrents"

e_arrow "Disabling download confirmation prompt"
defaults write org.m0k.transmission DownloadAsk -bool false

e_arrow "Trash original torrent files"
defaults write org.m0k.transmission DeleteOriginalTorrent -bool true

e_arrow "Hiding donate message"
defaults write org.m0k.transmission WarningDonate -bool false

e_arrow "Hiding the legal disclaimer"
defaults write org.m0k.transmission WarningLegal -bool false

###############################################################################
e_header "Restart affected applications"
###############################################################################

for app in "Address Book" "Calendar" "Contacts" "Dock" "Finder" "Mail" \
  "Messages" "Safari" "SystemUIServer" "Terminal" "Transmission" \
  "iCal" "Calendar"; do
  killall "${app}" > /dev/null 2>&1
done

echo ""
e_success "Done. Note that some of these changes require a logout/restart to take effect."
