#!/usr/bin/env bash

# Pretty pictures
function e_header()  { echo -e "\n\033[1m$@\033[0m";      }
function e_success() { echo -e " \033[1;32m✔\033[0m  $@"; }
function e_error()   { echo -e " \033[1;31m✖\033[0m  $@"; }
function e_arrow()   { echo -e "\033[1;34m==>\033[0m $@"; }

e_header "Setting OS X defaults"

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until `default` has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

###############################################################################
e_header "General UI/UX"
###############################################################################

e_arrow "Setting computer name"
sudo scutil --set ComputerName "Icarus"
sudo scutil --set HostName "Icarus"
sudo scutil --set LocalHostName "Icarus"
sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.smb.server NetBIOSName -string "Icarus"

e_arrow "Setting standby delay to 24 hours"
sudo pmset -a standbydelay 86400

# e_arrow "Disabling sound effects on boot"
# sudo nvram SystemAudioVolume=" "

# e_arrow "Disabling menubar transparency"
# defaults write NSGlobalDomain AppleEnableMenuBarTransparency -bool false

e_arrow "Configuring menubar battery time and percentage"
defaults write com.apple.menuextra.battery ShowPercent -string "NO"
defaults write com.apple.menuextra.battery ShowTime -string "YES"

e_arrow "Hiding Time Machine and Volume menubar icons"
defaults write com.apple.systemuiserver menuExtras -array "/System/Library/CoreServices/Menu Extras/Bluetooth.menu" "/System/Library/CoreServices/Menu Extras/AirPort.menu" "/System/Library/CoreServices/Menu Extras/Battery.menu" "/System/Library/CoreServices/Menu Extras/Clock.menu"

e_arrow "Setting sidebar icon size to small"
defaults write NSGlobalDomain NSTableViewDefaultSizeMode -int 1

e_arrow "Always show scrollbars"
defaults write NSGlobalDomain AppleShowScrollBars -string "Always"
# Possible values: `WhenScrolling`, `Automatic` and `Always`

e_arrow "Increasing window resize speed"
defaults write NSGlobalDomain NSWindowResizeTime -float 0.001

e_arrow "Expanding save panel by default"
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true

e_arrow "Expanding print panel by default"
defaults write NSGlobalDomain PMPrintingExpandedStateForPrint -bool true

e_arrow "Setting disk as default when saving"
defaults write NSGlobalDomain NSDocumentSaveNewDocumentsToCloud -bool false

e_arrow "Automatically quit printer app when print jobs complete"
defaults write com.apple.print.PrintingPrefs "Quit When Finished" -bool true

e_arrow "Disabling confirm open application dialog"
defaults write com.apple.LaunchServices LSQuarantine -bool false

# Try e.g. `cd /tmp; unidecode "\x{0000}" > cc.txt; open -e cc.txt`
e_arrow "Displaying ASCII control characters using caret notation"
defaults write NSGlobalDomain NSTextShowsControlCharacters -bool true

e_arrow "Disabling resume system-wide"
defaults write NSGlobalDomain NSQuitAlwaysKeepsWindows -bool false

e_arrow "Disabling automatic termination of inactive apps"
defaults write NSGlobalDomain NSDisableAutomaticTermination -bool true

# e_arrow "Disabling the crash reporter"
# defaults write com.apple.CrashReporter DialogType -string "none"

e_arrow "Setting Help Viewer windows to non-floating mode"
defaults write com.apple.helpviewer DevMode -bool true

e_arrow "Reveal IP address, hostname, OS version when clicking clock in login window"
sudo defaults write /Library/Preferences/com.apple.loginwindow AdminHostInfo HostName

# e_arrow "Disabling sleep mode"
# systemsetup -setcomputersleep Off > /dev/null

e_arrow "Check for software updates daily"
defaults write com.apple.SoftwareUpdate ScheduleFrequency -int 1

e_arrow "Disabling Notification Center"
launchctl unload -w /System/Library/LaunchAgents/com.apple.notificationcenterui.plist 2> /dev/null

e_arrow "Disabling smart quotes"
defaults write NSGlobalDomain NSAutomaticQuoteSubstitutionEnabled -bool false

e_arrow "Disabling smart dashes"
defaults write NSGlobalDomain NSAutomaticDashSubstitutionEnabled -bool false

###############################################################################
e_header "SSD-specific tweaks"
###############################################################################

e_arrow "Disabling local Time Machine snapshots"
sudo tmutil disablelocal

e_arrow "Disabling hibernation" # (speeds up entering sleep mode)
sudo pmset -a hibernatemode 0

e_arrow "Removing sleep image file" # to save disk space
sudo rm -f /Private/var/vm/sleepimage
# Create a zero-byte file instead…
sudo touch /Private/var/vm/sleepimage
# …and make sure it can’t be rewritten
sudo chflags uchg /Private/var/vm/sleepimage

e_arrow "Disabling sudden motion sensor" # not useful for SSDs
sudo pmset -a sms 0

###############################################################################
e_header "Trackpad, mouse, keyboard, Bluetooth accessories, and input"
###############################################################################

e_arrow "Enabling tap to click for this user and for the login screen"
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true
defaults -currentHost write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
defaults write NSGlobalDomain com.apple.mouse.tapBehavior -int 1

e_arrow "Setting mouse tracking speed"
defaults write NSGlobalDoman com.apple.mouse.scaling 3.0
# defaults delete NSGlobalDoman com.apple.mouse.scaling

e_arrow "Increasing sound quality for Bluetooth headphones/headsets"
defaults write com.apple.BluetoothAudioAgent "Apple Bitpool Min (editable)" -int 40

e_arrow "Enabling full keyboard access for all controls"
# (e.g. enable Tab in modal dialogs)
defaults write NSGlobalDomain AppleKeyboardUIMode -int 3

e_arrow "Enabling scroll gesture with Ctrl (^) modifier to zoom"
defaults write com.apple.universalaccess closeViewScrollWheelToggle -bool true
defaults write com.apple.universalaccess HIDScrollZoomModifierMask -int 262144

e_arrow "Map Caps Lock key to Control"
defaults -currentHost write -g com.apple.keyboard.modifiermapping '({HIDKeyboardModifierMappingSrc=0; HIDKeyboardModifierMappingDst=2;})'
defaults -currentHost write -g com.apple.keyboard.modifiermapping.1452-597-0 '({HIDKeyboardModifierMappingSrc=0; HIDKeyboardModifierMappingDst=2;})'

e_arrow "Follow the keyboard focus while zoomed in"
defaults write com.apple.universalaccess closeViewZoomFollowsFocus -bool true

e_arrow "Disabling press-and-hold for keys" # in favor of key repeat
defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool false

e_arrow "Setting keyboard repeat rate" # really fast
defaults write NSGlobalDomain KeyRepeat -int 0

e_arrow "Enabling automatic illumination for built-in MacBook keyboard"
defaults write com.apple.BezelServices kDim -bool true

e_arrow "Setting 5 minute timeout for keyboard illumination"
defaults write com.apple.BezelServices kDimTime -int 300

e_arrow "Setting default timezone" # see `systemsetup -listtimezones` for other values
systemsetup -settimezone "America/Detroit" > /dev/null

# e_arrow "Disable auto-correct"
# defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool false

# e_arrow "Disabling iTunes from responding to the keyboard media keys"
# launchctl unload -w /System/Library/LaunchAgents/com.apple.rcd.plist 2> /dev/null

###############################################################################
e_header "Screen"
###############################################################################

e_arrow "Requiring password immediately after sleep or screen saver begins"
defaults write com.apple.screensaver askForPassword -int 1
defaults write com.apple.screensaver askForPasswordDelay -int 0

e_arrow "Save screenshots to the desktop"
defaults write com.apple.screencapture location -string "${HOME}/Desktop"

e_arrow "Save screenshots in PNG format" # (other options: BMP, GIF, JPG, PDF, TIFF)
defaults write com.apple.screencapture type -string "png"

# e_arrow "Disabling shadows in screenshots"
# defaults write com.apple.screencapture disable-shadow -bool true

e_arrow "Enabling subpixel font rendering on non-Apple LCDs"
defaults write NSGlobalDomain AppleFontSmoothing -int 2

e_arrow "Enabling HiDPI display modes" # (requires restart)
sudo defaults write /Library/Preferences/com.apple.windowserver DisplayResolutionEnabled -bool true

###############################################################################
e_header "Finder"
###############################################################################

# e_arrow "Finder: allow quitting via ⌘ + Q; doing so will also hide desktop icons"
# defaults write com.apple.finder QuitMenuItem -bool true

# e_arrow "Disabling Finder window and Get Info animations"
# defaults write com.apple.finder DisableAllAnimations -bool true

# e_arrow "Showing icons for hard drives, servers, and removable media on the desktop"
# defaults write com.apple.finder ShowExternalHardDrivesOnDesktop -bool true
# defaults write com.apple.finder ShowHardDrivesOnDesktop -bool true
# defaults write com.apple.finder ShowMountedServersOnDesktop -bool true
# defaults write com.apple.finder ShowRemovableMediaOnDesktop -bool true

# e_arrow "Showing hidden files in Finder"
# defaults write com.apple.finder AppleShowAllFiles -bool true

e_arrow "Showing all filename extensions in Finder"
defaults write NSGlobalDomain AppleShowAllExtensions -bool true

e_arrow "Showing status bar in Finder"
defaults write com.apple.finder ShowStatusBar -bool true

e_arrow "Showing path bar in Finder"
defaults write com.apple.finder ShowPathbar -bool true

e_arrow "Allowing text selection in Quick Look"
defaults write com.apple.finder QLEnableTextSelection -bool true

e_arrow "Displaying full POSIX path as Finder window title"
defaults write com.apple.finder _FXShowPosixPathInTitle -bool true

e_arrow "Enabling searching of the current folder by default"
defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"

e_arrow "Disabling file extension change warning"
defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false

e_arrow "Enabling spring loading for directories"
defaults write NSGlobalDomain com.apple.springing.enabled -bool true

e_arrow "Removing spring loading delay for directories"
defaults write NSGlobalDomain com.apple.springing.delay -float 0

e_arrow "Disabling creation of .DS_Store files on network volumes"
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true

e_arrow "Disabling disk image verification"
defaults write com.apple.frameworks.diskimages skip-verify -bool true
defaults write com.apple.frameworks.diskimages skip-verify-locked -bool true
defaults write com.apple.frameworks.diskimages skip-verify-remote -bool true

e_arrow "Automatically open a new Finder window when a volume is mounted"
defaults write com.apple.frameworks.diskimages auto-open-ro-root -bool true
defaults write com.apple.frameworks.diskimages auto-open-rw-root -bool true
defaults write com.apple.finder OpenWindowForNewRemovableDisk -bool true

# e_arrow "Show item info near icons on the desktop and in other icon views"
# /usr/libexec/PlistBuddy -c "Set :DesktopViewSettings:IconViewSettings:showItemInfo true" ~/Library/Preferences/com.apple.finder.plist
# /usr/libexec/PlistBuddy -c "Set :FK_StandardViewSettings:IconViewSettings:showItemInfo true" ~/Library/Preferences/com.apple.finder.plist
# /usr/libexec/PlistBuddy -c "Set :StandardViewSettings:IconViewSettings:showItemInfo true" ~/Library/Preferences/com.apple.finder.plist

# e_arrow "Show item info to the right of the icons on the desktop"
# /usr/libexec/PlistBuddy -c "Set DesktopViewSettings:IconViewSettings:labelOnBottom false" ~/Library/Preferences/com.apple.finder.plist

e_arrow "Enabling snap-to-grid for the desktop and icon views"
/usr/libexec/PlistBuddy -c "Set :DesktopViewSettings:IconViewSettings:arrangeBy grid" ~/Library/Preferences/com.apple.finder.plist
/usr/libexec/PlistBuddy -c "Set :FK_StandardViewSettings:IconViewSettings:arrangeBy grid" ~/Library/Preferences/com.apple.finder.plist
/usr/libexec/PlistBuddy -c "Set :StandardViewSettings:IconViewSettings:arrangeBy grid" ~/Library/Preferences/com.apple.finder.plist

e_arrow "Increasing grid spacing for desktop and icon views"
/usr/libexec/PlistBuddy -c "Set :DesktopViewSettings:IconViewSettings:gridSpacing 100" ~/Library/Preferences/com.apple.finder.plist
/usr/libexec/PlistBuddy -c "Set :FK_StandardViewSettings:IconViewSettings:gridSpacing 100" ~/Library/Preferences/com.apple.finder.plist
/usr/libexec/PlistBuddy -c "Set :StandardViewSettings:IconViewSettings:gridSpacing 100" ~/Library/Preferences/com.apple.finder.plist

e_arrow "Increasing the size of icons on the desktop and in icon views"
/usr/libexec/PlistBuddy -c "Set :DesktopViewSettings:IconViewSettings:iconSize 80" ~/Library/Preferences/com.apple.finder.plist
/usr/libexec/PlistBuddy -c "Set :FK_StandardViewSettings:IconViewSettings:iconSize 80" ~/Library/Preferences/com.apple.finder.plist
/usr/libexec/PlistBuddy -c "Set :StandardViewSettings:IconViewSettings:iconSize 80" ~/Library/Preferences/com.apple.finder.plist

e_arrow "Setting list view as default Finder view"
# Four-letter codes for the other view modes: `icnv`, `clmv`, `Flwv`
defaults write com.apple.finder FXPreferredViewStyle -string "Nlsv"

e_arrow "Disabling warning before emptying the Trash"
defaults write com.apple.finder WarnOnEmptyTrash -bool false

e_arrow "Setting empty Trash securely as default"
defaults write com.apple.finder EmptyTrashSecurely -bool true

e_arrow "Enabling AirDrop over Ethernet and on unsupported Macs running Lion"
defaults write com.apple.NetworkBrowser BrowseAllInterfaces -bool true

e_arrow "Enabling the MacBook Air SuperDrive on any Mac"
sudo nvram boot-args="mbasd=1"

e_arrow "Showing the ~/Library folder"
chflags nohidden ~/Library

e_arrow "Removing Dropbox’s green checkmark icons in Finder"
file=/Applications/Dropbox.app/Contents/Resources/emblem-dropbox-uptodate.icns
[ -e "${file}" ] && mv -f "${file}" "${file}.bak"

###############################################################################
e_header "Dock and Dashboard"
###############################################################################
exit 1;
e_arrow "Enable highlight hover effect for the grid view of a stack (Dock)
defaults write com.apple.dock mouse-over-hilite-stack -bool true

e_arrow "Set the icon size of Dock items to 36 pixels
defaults write com.apple.dock tilesize -int 36

e_arrow "Minimize windows into their application’s icon
defaults write com.apple.dock minimize-to-application -bool true

e_arrow "Enable spring loading for all Dock items
defaults write com.apple.dock enable-spring-load-actions-on-all-items -bool true

e_arrow "Show indicator lights for open applications in the Dock
defaults write com.apple.dock show-process-indicators -bool true

e_arrow "Wipe all (default) app icons from the Dock
# This is only really useful when setting up a new Mac, or if you don’t use
# the Dock to launch apps.
# defaults write com.apple.dock persistent-apps -array

e_arrow "Don’t animate opening applications from the Dock
defaults write com.apple.dock launchanim -bool false

e_arrow "Speed up Mission Control animations
defaults write com.apple.dock expose-animation-duration -float 0.1

e_arrow "Don’t group windows by application in Mission Control
# (i.e. use the old Exposé behavior instead)
defaults write com.apple.dock expose-group-by-app -bool false

e_arrow "Disable Dashboard
defaults write com.apple.dashboard mcx-disabled -bool true

e_arrow "Don’t show Dashboard as a Space
defaults write com.apple.dock dashboard-in-overlay -bool true

e_arrow "Don’t automatically rearrange Spaces based on most recent use
defaults write com.apple.dock mru-spaces -bool false

e_arrow "Remove the auto-hiding Dock delay
# defaults write com.apple.dock autohide-delay -float 0

e_arrow "Remove the animation when hiding/showing the Dock
# defaults write com.apple.dock autohide-time-modifier -float 0

e_arrow "Enable the 2D Dock
# defaults write com.apple.dock no-glass -bool true

e_arrow "Automatically hide and show the Dock
defaults write com.apple.dock autohide -bool true

e_arrow "Make Dock icons of hidden applications translucent
defaults write com.apple.dock showhidden -bool true

e_arrow "Reset Launchpad
find ~/Library/Application\ Support/Dock -name "*.db" -maxdepth 1 -delete

e_arrow "Add iOS Simulator to Launchpad
sudo ln -sf /Applications/Xcode.app/Contents/Applications/iPhone\ Simulator.app /Applications/iOS\ Simulator.app

###############################################################################
e_header "Safari & WebKit"
###############################################################################

e_arrow "Set Safari’s home page to `about:blank` for faster loading
defaults write com.apple.Safari HomePage -string "about:blank"

e_arrow "Prevent Safari from opening ‘safe’ files automatically after downloading
defaults write com.apple.Safari AutoOpenSafeDownloads -bool false

e_arrow "Allow hitting the Backspace key to go to the previous page in history
defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2BackspaceKeyNavigationEnabled -bool true

e_arrow "Hide Safari’s bookmarks bar by default
# defaults write com.apple.Safari ShowFavoritesBar -bool false

e_arrow "Disable Safari’s thumbnail cache for History and Top Sites
defaults write com.apple.Safari DebugSnapshotsUpdatePolicy -int 2

e_arrow "Enable Safari’s debug menu
defaults write com.apple.Safari IncludeInternalDebugMenu -bool true

e_arrow "Make Safari’s search banners default to Contains instead of Starts With
defaults write com.apple.Safari FindOnPageMatchesWordStartsOnly -bool false

e_arrow "Remove useless icons from Safari’s bookmarks bar
defaults write com.apple.Safari ProxiesInBookmarksBar "()"

e_arrow "Enable the Develop menu and the Web Inspector in Safari
defaults write com.apple.Safari IncludeDevelopMenu -bool true
defaults write com.apple.Safari WebKitDeveloperExtrasEnabledPreferenceKey -bool true
defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled -bool true

e_arrow "Add a context menu item for showing the Web Inspector in web views
defaults write NSGlobalDomain WebKitDeveloperExtras -bool true

###############################################################################
e_header "Mail"
###############################################################################

e_arrow "Disable send and reply animations in Mail.app
# defaults write com.apple.mail DisableReplyAnimations -bool true
# defaults write com.apple.mail DisableSendAnimations -bool true

e_arrow "Copy email addresses as `foo@example.com` instead of `Foo Bar <foo@example.com>` in Mail.app
defaults write com.apple.mail AddressesIncludeNameOnPasteboard -bool false

e_arrow "Add the keyboard shortcut ⌘ + Enter to send an email in Mail.app
defaults write com.apple.mail NSUserKeyEquivalents -dict-add "Send" -string "@\\U21a9"

e_arrow "Display emails in threaded mode, sorted by date (oldest at the top)
# defaults write com.apple.mail DraftsViewerAttributes -dict-add "DisplayInThreadedMode" -string "yes"
# defaults write com.apple.mail DraftsViewerAttributes -dict-add "SortedDescending" -string "yes"
# defaults write com.apple.mail DraftsViewerAttributes -dict-add "SortOrder" -string "received-date"

e_arrow "Disable inline attachments (just show the icons)
defaults write com.apple.mail DisableInlineAttachmentViewing -bool true

e_arrow "Disable automatic spell checking
# defaults write com.apple.mail SpellCheckingBehavior -string "NoSpellCheckingEnabled"

###############################################################################
e_header "Spotlight"
###############################################################################

e_arrow "Hide Spotlight tray-icon (and subsequent helper)
sudo chmod 600 /System/Library/CoreServices/Search.bundle/Contents/MacOS/Search

e_arrow "Disable Spotlight indexing for any volume that gets mounted and has not yet
# been indexed before.
# Use `sudo mdutil -i off "/Volumes/foo"` to stop indexing any volume.
sudo defaults write /.Spotlight-V100/VolumeConfiguration Exclusions -array "/Volumes"

e_arrow "Change indexing order and disable some file types
defaults write com.apple.spotlight orderedItems -array \
	'{"enabled" = 1;"name" = "APPLICATIONS";}' \
	'{"enabled" = 1;"name" = "SYSTEM_PREFS";}' \
	'{"enabled" = 1;"name" = "DIRECTORIES";}' \
	'{"enabled" = 1;"name" = "PDF";}' \
	'{"enabled" = 1;"name" = "DOCUMENTS";}' \
	'{"enabled" = 0;"name" = "FONTS";}' \
	'{"enabled" = 0;"name" = "MESSAGES";}' \
	'{"enabled" = 0;"name" = "CONTACT";}' \
	'{"enabled" = 0;"name" = "EVENT_TODO";}' \
	'{"enabled" = 0;"name" = "IMAGES";}' \
	'{"enabled" = 0;"name" = "BOOKMARKS";}' \
	'{"enabled" = 0;"name" = "MUSIC";}' \
	'{"enabled" = 0;"name" = "MOVIES";}' \
	'{"enabled" = 0;"name" = "PRESENTATIONS";}' \
	'{"enabled" = 0;"name" = "SPREADSHEETS";}' \
	'{"enabled" = 0;"name" = "SOURCE";}'

e_arrow "Load new settings before rebuilding the index
killall mds > /dev/null 2>&1

e_arrow "Make sure indexing is enabled for the main volume
sudo mdutil -i on / > /dev/null

e_arrow "Rebuild the index from scratch
sudo mdutil -E / > /dev/null

###############################################################################
e_header "Terminal & iTerm 2"
###############################################################################

e_arrow "Only use UTF-8 in Terminal.app
defaults write com.apple.terminal StringEncodings -array 4

e_arrow "Use a modified version of the Pro theme by default in Terminal.app
open "${HOME}/init/Mathias.terminal"
sleep 1 # Wait a bit to make sure the theme is loaded
defaults write com.apple.terminal "Default Window Settings" -string "Mathias"
defaults write com.apple.terminal "Startup Window Settings" -string "Mathias"

e_arrow "Enable “focus follows mouse” for Terminal.app and all X11 apps
# i.e. hover over a window and start typing in it without clicking first
# defaults write com.apple.terminal FocusFollowsMouse -bool true
# defaults write org.x.X11 wm_ffm -bool true

e_arrow "Install pretty iTerm colors
open "${HOME}/init/Mathias.itermcolors"

e_arrow "Don’t display the annoying prompt when quitting iTerm
defaults write com.googlecode.iterm2 PromptOnQuit -bool false

###############################################################################
e_header "Time Machine"
###############################################################################

e_arrow "Prevent Time Machine from prompting to use new hard drives as backup volume
defaults write com.apple.TimeMachine DoNotOfferNewDisksForBackup -bool true

e_arrow "Disable local Time Machine backups
hash tmutil &> /dev/null && sudo tmutil disablelocal

###############################################################################
e_header "Address Book, Dashboard, Calendar, TextEdit, and Disk Utility"
###############################################################################

e_arrow "Enable the debug menu in Address Book
defaults write com.apple.addressbook ABShowDebugMenu -bool true

e_arrow "Enable Dashboard dev mode (allows keeping widgets on the desktop)
defaults write com.apple.dashboard devmode -bool true

e_arrow "Use plain text mode for new TextEdit documents
defaults write com.apple.TextEdit RichText -int 0

e_arrow "Open and save files as UTF-8 in TextEdit
defaults write com.apple.TextEdit PlainTextEncoding -int 4
defaults write com.apple.TextEdit PlainTextEncodingForWrite -int 4

e_arrow "Enable the debug menu in Disk Utility
defaults write com.apple.DiskUtility DUDebugMenuEnabled -bool true
defaults write com.apple.DiskUtility advanced-image-options -bool true

###############################################################################
e_header "Mac App Store"
###############################################################################

e_arrow "Enable the WebKit Developer Tools in the Mac App Store
defaults write com.apple.appstore WebKitDeveloperExtras -bool true

e_arrow "Enable Debug Menu in the Mac App Store
defaults write com.apple.appstore ShowDebugMenu -bool true

###############################################################################
e_header "Messages"
###############################################################################

e_arrow "Disable automatic emoji substitution (i.e. use plain text smileys)
defaults write com.apple.messageshelper.MessageController SOInputLineSettings -dict-add "automaticEmojiSubstitutionEnablediMessage" -bool false

e_arrow "Disable smart quotes as it’s annoying for messages that contain code
defaults write com.apple.messageshelper.MessageController SOInputLineSettings -dict-add "automaticQuoteSubstitutionEnabled" -bool false

e_arrow "Disable continuous spell checking
# defaults write com.apple.messageshelper.MessageController SOInputLineSettings -dict-add "continuousSpellCheckingEnabled" -bool false

###############################################################################
e_header "Sublime Text"
###############################################################################

e_arrow "Install Sublime Text settings
cp -r init/Preferences.sublime-settings ~/Library/Application\ Support/Sublime\ Text*/Packages/User/Preferences.sublime-settings 2> /dev/null

###############################################################################
e_header "Transmission"
###############################################################################

e_arrow "Use `~/Documents/Torrents` to store incomplete downloads
defaults write org.m0k.transmission UseIncompleteDownloadFolder -bool true
defaults write org.m0k.transmission IncompleteDownloadFolder -string "${HOME}/Documents/Torrents"

e_arrow "Don’t prompt for confirmation before downloading
defaults write org.m0k.transmission DownloadAsk -bool false

e_arrow "Trash original torrent files
defaults write org.m0k.transmission DeleteOriginalTorrent -bool true

e_arrow "Hide the donate message
defaults write org.m0k.transmission WarningDonate -bool false

e_arrow "Hide the legal disclaimer
defaults write org.m0k.transmission WarningLegal -bool false

###############################################################################
e_header "Restart affected applications"
###############################################################################

for app in "Address Book" "Calendar" "Contacts" "Dock" "Finder" "Mail" \
	"Messages" "Safari" "SystemUIServer" "Terminal" "Transmission" \
	"iCal"; do
	killall "${app}" > /dev/null 2>&1
done

e_success "Done. Note that some of these changes require a logout/restart to take effect."
