alias g='git'
alias gap='git add -p'
alias gbd='git branch -d'
alias gbD='git branch -D'
alias gc='git clone'
alias gcp='git cherry-pick'
alias gcu='git_clean'
alias gdf='git diff'
alias gl='pretty_git_log'
alias gll='git log --graph --pretty=oneline --abbrev-commit'
alias gpo='git push origin'
alias grb='git rebase'
alias gri='git rebase -i'
alias grc='git rebase --continue'
alias gra='git rebase --abort'
alias gst='git status'
alias gf='git fetch'

alias gfr='git fetch && git rebase'
alias gfrm='git fetch && git rebase origin/master'
alias gcb='git checkout -b'
alias gco='git checkout'
alias gcom='gco master'
alias gpr='git pull --rebase'
